### ISSUE TITLE
PowerShell 7 issue

### ISSUE THREAD

**Issue by troystaylor** [ZanattaMichael/SelMVP#61]
I'm getting the following error when I try to use this:
![image](https://user-images.githubusercontent.com/44444967/217653614-36649a6f-3a3c-4a66-94d4-08743eacf62c.png)

**Comment by ZanattaMichael** [comment]
Hi Troy,

Are you using PowerShell 7.0 or Windows PowerShell 5.1?

Thanks,

Michael.

Sent from my iPhone

On 9 Feb 2023, at 7:21 am, Troy Taylor ***@***.***> wrote:

﻿

I'm getting the following error when I try to use this:
[image]<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F44444967%2F217653614-36649a6f-3a3c-4a66-94d4-08743eacf62c.png&data=05%7C01%7C%7Cc558d55fbfa544e0073708db0a1a6656%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638114880747936391%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Ip1ytJaWc5KjIDZVUQO3aMGaw%2BMva9lrIABF0%2FIhCYo%3D&reserved=0>

**Comment by troystaylor** [comment]
PowerShell 7 - do I need to use 5.1?

**Comment by troystaylor** [comment]
With 5.1, I get the following:

ConnectTo-MVPPortal -URLPath https://mvp.microsoft.com/en-us/MyProfile/EditActivity
Selenium MVP Module Loaded. Use 'ConnectTo-MVPPortal' to get started.
An Error occured when attempting to connect to the portal. Details: 'Exception calling ".ctor" with "2" argument(s):
"Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary'
capability provided, and no binary flag set on the command line (SessionNotCreated)"'
At C:\Program Files\WindowsPowerShell\Modules\SelMVP\1.0.2\Module.psm1:1692 char:9
+         Throw ($LocalizedData.ErrorConnectToMVPPortal -f $_)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (An Error occure...onNotCreated)"':String) [], RuntimeException
    + FullyQualifiedErrorId : An Error occured when attempting to connect to the portal. Details: 'Exception calling "
   .ctor" with "2" argument(s): "Expected browser binary location, but unable to find binary in default location, no
  'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line (SessionNotCreated)"'

**Comment by ZanattaMichael** [comment]
Yup 5.1.

Do you have Firefox installed and using the latest gecko driver?

Cheers,

Michael.

Sent from my iPhone

On 9 Feb 2023, at 8:11 am, Troy Taylor ***@***.***> wrote:

﻿

With 5.1, I get the following:

ConnectTo-MVPPortal -URLPath https://mvp.microsoft.com/en-us/MyProfile/EditActivity<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmvp.microsoft.com%2Fen-us%2FMyProfile%2FEditActivity&data=05%7C01%7C%7C8e1e2433fe9b423b7ebf08db0a216e38%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638114910953564812%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OR4P35KEHFlccO1SLfZHEpxX%2FlxYiLrRn%2F4cyDF571o%3D&reserved=0>
Selenium MVP Module Loaded. Use 'ConnectTo-MVPPortal' to get started.
An Error occured when attempting to connect to the portal. Details: 'Exception calling ".ctor" with "2" argument(s):
"Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary'
capability provided, and no binary flag set on the command line (SessionNotCreated)"'
At C:\Program Files\WindowsPowerShell\Modules\SelMVP\1.0.2\Module.psm1:1692 char:9

  *

    Throw ($LocalizedData.ErrorConnectToMVPPortal -f $_)


  *

    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


     *   CategoryInfo : OperationStopped: (An Error occure...onNotCreated)"':String) [], RuntimeException
     *   FullyQualifiedErrorId : An Error occured when attempting to connect to the portal. Details: 'Exception calling "
.ctor" with "2" argument(s): "Expected browser binary location, but unable to find binary in default location, no
'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line (SessionNotCreated)"'

—
Reply to this email directly, view it on GitHub<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FZanattaMichael%2FSelMVP%2Fissues%2F61%23issuecomment-1423307298&data=05%7C01%7C%7C8e1e2433fe9b423b7ebf08db0a216e38%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638114910953564812%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sgROLsm28NTFwQ17Ce9BBPnUaeLaXtKhtu590o6QZcA%3D&reserved=0>, or unsubscribe<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAF7JW5HTTEGL67R3DYIZ3LTWWQKZDANCNFSM6AAAAAAUVYMJD4&data=05%7C01%7C%7C8e1e2433fe9b423b7ebf08db0a216e38%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638114910953564812%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lChkskJ%2FxL1DNPOqYu41nONzOTIO8Q0QChUOkjOqlRQ%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.***>

**Comment by ZanattaMichael** [comment]
Hey @troystaylor. I recreated your issue and got to the bottom of it. The latest gecko build was a 32-bit built, and PSSelenium was trying to use access using a 64-bit browser. To resolve this issue, download the latest 64-bit version (https://github.com/mozilla/geckodriver/releases/download/v0.32.1/geckodriver-v0.32.1-win64.zip).

Thanks for letting me know. I'll raise an issue to update the documentation. :-P

**Comment by ZanattaMichael** [comment]
Linking #63 as well. Please close if you are happy with the solution. :-D
